---

- hosts: all
  become: true
  tasks:

  - name: install apache n php
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

