- name: install apache and php for Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_os_family == "Debian"

- name: install apache and php for CentOS servers
  tags: rocky,http,php
  shell: dnf install httpd* -y
  when: ansible_os_family == "RedHat"
  notify: start_httpd
